services:
 - name: revite-urls
   plan: free
   type: web
   env: python
   branch: main
   buildCommand: "pip install -r requirements.txt"
   startCommand: "uvicorn --port $PORT --host 0.0.0.0 main:app"
   envVars:
    - key: JSON_URL
      value: https://browser.jf6deu.net/json.php
